-- =====================================================================
-- OPCIONAL. Use este arquivo apenas se optar por controlar o schema
-- manualmente, com spring.jpa.hibernate.ddl-auto=none e
-- spring.sql.init.mode=always.
--
-- Com a configuracao padrao do projeto (ddl-auto=update), o Hibernate ja
-- cria e evolui estas tabelas: NAO mantenha este arquivo, ou os dois
-- mecanismos passam a disputar o controle do schema.
-- =====================================================================

CREATE TABLE IF NOT EXISTS perfis (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(30)  NOT NULL UNIQUE,
    descricao VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    username   VARCHAR(60)  NOT NULL UNIQUE,
    email      VARCHAR(150) NOT NULL UNIQUE,
    senha      VARCHAR(100) NOT NULL,
    ativo      BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em  TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_perfis (
    usuario_id BIGINT NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    perfil_id  BIGINT NOT NULL REFERENCES perfis (id),
    PRIMARY KEY (usuario_id, perfil_id)
);

CREATE TABLE IF NOT EXISTS destinos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(120)   NOT NULL,
    localizacao      VARCHAR(150)   NOT NULL,
    pais             VARCHAR(80)    NOT NULL,
    descricao        VARCHAR(1000)  NOT NULL,
    preco_base       NUMERIC(12, 2),
    avaliacao        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_avaliacoes INTEGER          NOT NULL DEFAULT 0,
    ativo            BOOLEAN          NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP        NOT NULL,
    atualizado_em    TIMESTAMP,
    CONSTRAINT uk_destino_nome_localizacao UNIQUE (nome, localizacao)
);

CREATE INDEX IF NOT EXISTS idx_destinos_pais ON destinos (pais);
CREATE INDEX IF NOT EXISTS idx_destinos_avaliacao ON destinos (avaliacao DESC);
